const $=id=>document.getElementById(id);const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const show=x=>JSON.stringify(x);async function request(text){const r=await fetch('/api',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});if(!r.ok)throw Error(await r.text());return r.json()}document.querySelectorAll('[data-port]').forEach(a=>a.href=location.protocol+'//'+location.hostname+':'+a.dataset.port);let data,index=0,source='';const notes={initial:'No word has started. There are no capitalization or digit facts yet.',startWord:'The first character starts a word and establishes its classification.',appendPrefix:'This consonant extends the prefix that will move to the end.',completeQu:'The u stays with the preceding q in the movable prefix.',startStem:'An eligible vowel starts the part that stays at the front.',appendStem:'This character extends the stem.',finish:'Commit the pending word and preserve the separator, or finish the complete input.',leadingQuote:'Preserve the opening quote before the word.',trailingPunctuation:'Commit the word and preserve punctuation at this boundary.'};
function render(){const s=data.steps[index],v=s.state;$('chars').innerHTML=[...source].map((c,i)=>`<span class="char ${i===s.position-1?'current':''}">${esc(c===' '?'␠':c==='\t'?'⇥':c==='\n'?'↵':c)}</span>`).join('');$('rule').textContent=s.rule;$('explain').textContent=notes[s.rule];$('output').textContent=v.output||'∅';$('state').innerHTML=Object.entries(v).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(typeof v==='object'?JSON.stringify(v,null,2):show(v))}</dd>`).join('');$('count').textContent=`Step ${index} / ${data.steps.length-1}`;$('back').disabled=index===0;$('next').disabled=index===data.steps.length-1;renderDiagram();renderTrace();}
let latestRequest=0;
async function load(){const requestId=++latestRequest;const requestedSource=$('input').value;$('walkthrough').hidden=true;try{const result=await request(requestedSource);if(requestId!==latestRequest)return;source=requestedSource;if(!result.ok){data=null;$('error').textContent='';$('contract').innerHTML='<h2>Rejected</h2><p>'+esc(result.error)+'</p><p>No translation or reducer walkthrough runs for this input.</p>';$('fragments').innerHTML='';$('walkthrough').hidden=true;return}$('error').textContent='';data=result;index=0;$('walkthrough').hidden=false;contract(source,result.output);render()}catch(e){if(requestId!==latestRequest)return;$('error').textContent=e.message;$('walkthrough').hidden=true}}
$('load').onclick=load;$('input').addEventListener('input',()=>{$('error').textContent='';$('contract').textContent='Updating…';$('fragments').innerHTML='';load()});$('back').onclick=()=>{index=Math.max(0,index-1);render()};$('next').onclick=()=>{index=Math.min(data.steps.length-1,index+1);render()};$('end').onclick=()=>{index=data.steps.length-1;render()};['Hello! queen','"SQUARE!!"','2?8','hello\tworld\n','1a','square','00123',''].forEach(text=>{const b=document.createElement('button');b.textContent=show(text);b.onclick=()=>{$('input').value=text;load()};$('presets').append(b)});load();
function contract(text,output){$('contract').innerHTML='<h2>Accepted</h2><div class="result">'+esc(show(output))+'</div>';const parts=text.match(/[ \t\n,!?"]|[^ \t\n,!?"]+/g)||[];$('fragments').innerHTML=parts.map(word=>{if(/^[ \t\n,!?"]$/.test(word)||/^\d+$/.test(word))return '<p><span class="tag">'+esc(show(word))+'</span> Preserved exactly</p>';const low=word.toLowerCase();let cut=[...low].findIndex((c,i)=>'aeiou'.includes(c)&&!(c==='u'&&i>0&&low[i-1]==='q'));if(cut<0)cut=low.length;const prefix=low.slice(0,cut),stem=low.slice(cut);return '<p><strong>'+esc(word)+'</strong> → <span class="tag">'+esc(stem||'∅')+'</span> + <span class="tag">'+esc(prefix||'∅')+'</span> + <span class="tag">ay</span> · restore '+(word===word.toUpperCase()?'uppercase':word[0]===word[0].toUpperCase()?'title case':'lowercase')+'</p>'}).join('')}
function renderDiagram(){const states=[...new Set(data.steps.map(step=>step.state.kind))],pos={leading:[130,65],prefix:[410,65],stem:[410,270],trailingPunctuation:[130,270]};const edges=new Map();for(let i=1;i<data.steps.length;i++){const a=data.steps[i-1].state.kind,b=data.steps[i].state.kind,key=a+'|'+b;if(!edges.has(key))edges.set(key,{a,b,rules:new Set()});edges.get(key).rules.add(data.steps[i].rule)}const current=data.steps[index].state.kind,prev=index?data.steps[index-1].state.kind:null;let drawing='';for(const {a,b,rules} of edges.values()){const [x,y]=pos[a],[xx,yy]=pos[b],active=prev===a&&current===b;let path;if(a===b)path=`M ${x-35} ${y-22} C ${x-90} ${y-85},${x+90} ${y-85},${x+35} ${y-22}`;else{const dx=xx-x,dy=yy-y,len=Math.hypot(dx,dy),ux=dx/len,uy=dy/len;path=`M ${x+ux*65} ${y+uy*30} Q ${(x+xx)/2-uy*25} ${(y+yy)/2+ux*25} ${xx-ux*65} ${yy-uy*30}`}drawing+=`<path class="edge ${active?'selected':''}" marker-end="url(#arrow)" d="${path}"><title>${esc(a+' → '+b+': '+[...rules].join(', '))}</title></path>`}for(const state of states){const [x,y]=pos[state];drawing+=`<g data-state="${state}" tabindex="0" role="button" aria-label="Jump to ${state}" title="Jump to the next occurrence of ${state}"><rect class="node ${state===current?'selected':''}" x="${x-85}" y="${y-25}" width="170" height="50" rx="12"/><text x="${x}" y="${y+5}" text-anchor="middle">${state}</text></g>`}$('state-diagram').innerHTML=`<h2>State diagram</h2><p>States visited by this input</p><div class="diagram"><svg viewBox="0 -25 550 360" role="img" aria-label="Observed reducer state transitions"><defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#245f4d"/></marker></defs>${drawing}</svg></div><p class="result">${esc(prev||'∅')} → ${esc(current)}</p><p>Event: <strong>${esc(show(data.steps[index].character))}</strong> · decision: <strong>${esc(data.steps[index].rule)}</strong></p>`;document.querySelectorAll('[data-state]').forEach(el=>{const jump=()=>{let found=data.steps.findIndex((s,i)=>i>index&&s.state.kind===el.dataset.state);if(found<0)found=data.steps.findIndex(s=>s.state.kind===el.dataset.state);if(found>=0){index=found;render()}};el.onclick=jump;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();jump()}}})}
function renderTrace(){const current=data.steps[index],before=index?data.steps[index-1].state:{};const delta=Object.keys(current.state).filter(k=>JSON.stringify(before[k])!==JSON.stringify(current.state[k])).map(k=>`<p><strong>${esc(k)}</strong> <code>${esc(show(before[k])??'absent')}</code> → <code class="changed">${esc(show(current.state[k]))}</code></p>`).join('');const removed=Object.keys(before).filter(k=>!(k in current.state)).map(k=>`<p><strong>${esc(k)}</strong> removed when the word was committed</p>`).join('');$('decision-trace').innerHTML=`<h2>Decision trace</h2><p>Every row is an actual reducer step. Select a row to inspect what changed.</p><div class="trace"><table><thead><tr><th>Step</th><th>Character</th><th>Decision</th><th>State</th><th>Prefix / stem</th><th>Committed output</th></tr></thead><tbody>${data.steps.map((s,i)=>`<tr class="${i===index?'selected':''}"><td><button data-step="${i}" aria-label="Select step ${i}">${i}</button></td><td>${esc(show(s.character))}</td><td>${esc(s.rule)}</td><td>${esc(s.state.kind)}</td><td>${esc(show(s.state.prefix??'')+' / '+show(s.state.stem??''))}</td><td>${esc(show(s.state.output))}</td></tr>`).join('')}</tbody></table></div><h2>Changes at step ${index}</h2>${delta+removed||'<p>No state fields changed.</p>'}`;document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{index=Number(b.dataset.step);render()});requestAnimationFrame(()=>keepSelectedRowVisible('decision-trace'))}

document.addEventListener('keydown',event=>{
  if(event.key!=='ArrowLeft'&&event.key!=='ArrowRight')return;
  if(event.altKey||event.ctrlKey||event.metaKey||event.shiftKey||event.isComposing)return;
  const target=event.target;
  if(target?.closest('input,textarea,select,[role="textbox"],[role="slider"]')||target?.isContentEditable)return;
  if(!data||$('walkthrough').hidden)return;
  event.preventDefault();
  const nextIndex=Math.max(0,Math.min(data.steps.length-1,index+(event.key==='ArrowRight'?1:-1)));
  if(nextIndex!==index){index=nextIndex;render()}
});

document.body.dataset.variant='A';

function keepSelectedRowVisible(panelId){
  const panel=$(panelId),container=panel.querySelector('.trace'),row=panel.querySelector('tr.selected');
  if(!container||!row||!container.clientHeight)return;
  const box=container.getBoundingClientRect(),selected=row.getBoundingClientRect();
  const header=container.querySelector('thead')?.getBoundingClientRect().height??0;
  const visibleTop=box.top+header,visibleBottom=box.top+container.clientHeight;
  if(selected.top<visibleTop||selected.bottom>visibleBottom){
    container.scrollTop+=selected.top-(visibleTop+(visibleBottom-visibleTop-selected.height)/2);
  }
}

